# Without a non-breaking space, brand names can be split in the middle, with the start and end on two different lines.
extends: substitution
message: Use a non-breaking space for brand name ('%s' instead of '%s')
level: error
ignorecase: true
# swap maps tokens in form of bad: good
# for more information: https://vale.sh/docs/topics/styles/#substitution
swap:
  Material UI: Material UI
  MUI X: MUI X
  Base UI: Base UI
  MUI System: MUI System
  MUI Store: MUI Store
  MUI Core: MUI Core
  MUI Toolpad: MUI Toolpad
  MUI Connect: MUI Connect
