extends: substitution
message: To be consistent with capitalization, consider using '%s' instead of '%s'.
level: error
ignorecase: false
# swap maps tokens in form of bad: good
# for more information: https://vale.sh/docs/topics/styles/#substitution
swap:
  api: API
  Api: API
  typescript: TypeScript
  Typescript: TypeScript
  ts: TypeScript
  TS: TypeScript
  javascript: JavaScript
  Javascript: JavaScript
  css: CSS
  Css: CSS
  NPM: npm # https://css-tricks.com/start-sentence-npm/
  Github: GitHub
