// This file is autogenerated. Do not edit it directly.
// To update it, modify the corresponding source file and run `pnpm inline-scripts`.

// prettier-ignore
export const script = '!function(){console.log("prehydration");const t=document.currentScript.previousElementSibling;if(!t)return void console.log("no indicator");const o=t.closest(\'[role="tablist"]\');if(!o)return void console.log("no list");const e=o.querySelector(\'[data-selected="true"]\');if(!e)return void console.log("no active tab");const{left:n,right:i,top:r,bottom:l,width:c}=e.getBoundingClientRect(),{left:s,right:g,top:d,bottom:u,width:p}=o.getBoundingClientRect();if(0===c||0===p)return;const a=g-i,f=r-d,h=u-l,b=i-n,v=l-r;function m(o,e){t.style.setProperty(`--active-tab-${o}`,`${e}px`),console.log("setting prop",o,e,t)}m("left",n-s),m("right",a),m("top",f),m("bottom",h),m("width",b),m("height",v)}();';
