commit_message: '[skip ci]'
pull_request_title: '[docs] Sync translations with Crowdin'
pull_request_labels: [l10n]
files:
  - source: /docs/src/**/*.md
    ignore:
      - /**/%file_name%-%two_letters_code%.md
      - /docs/src/pages/getting-started/templates/*/**/*
      - /docs/src/pages/premium-themes/*/**/*
      - /docs/src/pages/discover-more/backers/*
      - /docs/src/pages/discover-more/roadmap/*
      - /docs/src/pages/company/**/*
      - /docs/pages/careers/**/*
    translation: /%original_path%/%file_name%-%two_letters_code%.%file_extension%
  - source: /docs/data/**/*.md
    ignore:
      - /**/%file_name%-%two_letters_code%.md
      - /docs/data/material/getting-started/templates/*/**/*
      - /docs/data/material/discover-more/backers/*
      - /docs/data/material/discover-more/roadmap/*
      - /docs/data/material/premium-themes/*/**/*
    translation: /%original_path%/%file_name%-%two_letters_code%.%file_extension%
  - source: /docs/translations/**/*.json
    ignore:
      - /**/%file_name%-%two_letters_code%.json
    translation: /%original_path%/%file_name%-%two_letters_code%.%file_extension%
