packages:
  - packages/*
  - docs
  - test
  - test/*
  - scripts/*
  - examples/*
  - playground/*

allowBuilds:
  '@mui/internal-babel-plugin-display-name': true
  '@vvago/vale': true
  core-js: true
  esbuild: true
  nx: true
  sharp: true
  unrs-resolver: true

enablePrePostScripts: true
engineStrict: true
