/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComboboxServerFnRouteImport } from './routes/combobox-server-fn'
import { Route as IndexRouteImport } from './routes/index'

const ComboboxServerFnRoute = ComboboxServerFnRouteImport.update({
  id: '/combobox-server-fn',
  path: '/combobox-server-fn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combobox-server-fn': typeof ComboboxServerFnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combobox-server-fn': typeof ComboboxServerFnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combobox-server-fn': typeof ComboboxServerFnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/combobox-server-fn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/combobox-server-fn'
  id: '__root__' | '/' | '/combobox-server-fn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComboboxServerFnRoute: typeof ComboboxServerFnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/combobox-server-fn': {
      id: '/combobox-server-fn'
      path: '/combobox-server-fn'
      fullPath: '/combobox-server-fn'
      preLoaderRoute: typeof ComboboxServerFnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComboboxServerFnRoute: ComboboxServerFnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
