// This file is autogenerated. Do not edit it directly.
// To update it, modify the corresponding source file and run `pnpm inline-scripts`.

// prettier-ignore
export const script = '!function(){const t=document.currentScript.previousElementSibling;if(!t)return;const e=t.closest(\'[role="tablist"]\');if(!e)return;const i=e.querySelector("[data-active]");if(!i)return;if(0===i.offsetWidth||0===e.offsetWidth)return;const o=getComputedStyle(e).direction;let f=0,n=0,r=0,l=0,c=0,s=0;if(null!=i&&null!=e){f=i.offsetLeft,r=i.offsetTop;const{width:t,height:u}=i.getBoundingClientRect();c=t,s=u,n="ltr"===o?e.scrollWidth-i.offsetLeft-c-e.clientLeft:i.offsetLeft-e.clientLeft,l=e.scrollHeight-i.offsetTop-s-e.clientTop}function u(e,i){t.style.setProperty(`--active-tab-${e}`,`${i}px`)}u("left",f),u("right",n),u("top",r),u("bottom",l),u("width",c),u("height",s),c>0&&s>0&&t.removeAttribute("hidden")}();';
