'use client';
export { appendOwnerState } from '../legacy/utils/appendOwnerState';
export { areArraysEqual } from './areArraysEqual';
export { ClassNameConfigurator } from '../legacy/utils/ClassNameConfigurator';
export { extractEventHandlers } from './extractEventHandlers';
export { isHostComponent } from './isHostComponent';
export { resolveComponentProps } from '../legacy/utils/resolveComponentProps';
export { useRootElementName } from './useRootElementName';
export { useSlotProps } from '../legacy/utils/useSlotProps';
export { mergeSlotProps } from '../legacy/utils/mergeSlotProps';
export { prepareForSlot } from './prepareForSlot';
export * from '../legacy/utils/PolymorphicComponent';
export * from './types';
