export interface Country {
  code: string;
  value: string;
  continent: string;
}

export const countries: Country[] = [
  { code: 'af', value: 'Afghanistan', continent: 'Asia' },
  { code: 'al', value: 'Albania', continent: 'Europe' },
  { code: 'dz', value: 'Algeria', continent: 'Africa' },
  { code: 'ad', value: 'Andorra', continent: 'Europe' },
  { code: 'ao', value: 'Angola', continent: 'Africa' },
  { code: 'ar', value: 'Argentina', continent: 'South America' },
  { code: 'am', value: 'Armenia', continent: 'Asia' },
  { code: 'au', value: 'Australia', continent: 'Oceania' },
  { code: 'at', value: 'Austria', continent: 'Europe' },
  { code: 'az', value: 'Azerbaijan', continent: 'Asia' },
  { code: 'bs', value: 'Bahamas', continent: 'North America' },
  { code: 'bh', value: 'Bahrain', continent: 'Asia' },
  { code: 'bd', value: 'Bangladesh', continent: 'Asia' },
  { code: 'bb', value: 'Barbados', continent: 'North America' },
  { code: 'by', value: 'Belarus', continent: 'Europe' },
  { code: 'be', value: 'Belgium', continent: 'Europe' },
  { code: 'bz', value: 'Belize', continent: 'North America' },
  { code: 'bj', value: 'Benin', continent: 'Africa' },
  { code: 'bt', value: 'Bhutan', continent: 'Asia' },
  { code: 'bo', value: 'Bolivia', continent: 'South America' },
  { code: 'ba', value: 'Bosnia and Herzegovina', continent: 'Europe' },
  { code: 'bw', value: 'Botswana', continent: 'Africa' },
  { code: 'br', value: 'Brazil', continent: 'South America' },
  { code: 'bn', value: 'Brunei', continent: 'Asia' },
  { code: 'bg', value: 'Bulgaria', continent: 'Europe' },
  { code: 'bf', value: 'Burkina Faso', continent: 'Africa' },
  { code: 'bi', value: 'Burundi', continent: 'Africa' },
  { code: 'kh', value: 'Cambodia', continent: 'Asia' },
  { code: 'cm', value: 'Cameroon', continent: 'Africa' },
  { code: 'ca', value: 'Canada', continent: 'North America' },
  { code: 'cv', value: 'Cape Verde', continent: 'Africa' },
  { code: 'cf', value: 'Central African Republic', continent: 'Africa' },
  { code: 'td', value: 'Chad', continent: 'Africa' },
  { code: 'cl', value: 'Chile', continent: 'South America' },
  { code: 'cn', value: 'China', continent: 'Asia' },
  { code: 'co', value: 'Colombia', continent: 'South America' },
  { code: 'km', value: 'Comoros', continent: 'Africa' },
  { code: 'cg', value: 'Congo', continent: 'Africa' },
  { code: 'cr', value: 'Costa Rica', continent: 'North America' },
  { code: 'hr', value: 'Croatia', continent: 'Europe' },
  { code: 'cu', value: 'Cuba', continent: 'North America' },
  { code: 'cy', value: 'Cyprus', continent: 'Asia' },
  { code: 'cz', value: 'Czech Republic', continent: 'Europe' },
  { code: 'dk', value: 'Denmark', continent: 'Europe' },
  { code: 'dj', value: 'Djibouti', continent: 'Africa' },
  { code: 'dm', value: 'Dominica', continent: 'North America' },
  { code: 'do', value: 'Dominican Republic', continent: 'North America' },
  { code: 'ec', value: 'Ecuador', continent: 'South America' },
  { code: 'eg', value: 'Egypt', continent: 'Africa' },
  { code: 'sv', value: 'El Salvador', continent: 'North America' },
  { code: 'gq', value: 'Equatorial Guinea', continent: 'Africa' },
  { code: 'er', value: 'Eritrea', continent: 'Africa' },
  { code: 'ee', value: 'Estonia', continent: 'Europe' },
  { code: 'et', value: 'Ethiopia', continent: 'Africa' },
  { code: 'fj', value: 'Fiji', continent: 'Oceania' },
  { code: 'fi', value: 'Finland', continent: 'Europe' },
  { code: 'fr', value: 'France', continent: 'Europe' },
  { code: 'ga', value: 'Gabon', continent: 'Africa' },
  { code: 'gm', value: 'Gambia', continent: 'Africa' },
  { code: 'ge', value: 'Georgia', continent: 'Asia' },
  { code: 'de', value: 'Germany', continent: 'Europe' },
  { code: 'gh', value: 'Ghana', continent: 'Africa' },
  { code: 'gr', value: 'Greece', continent: 'Europe' },
  { code: 'gd', value: 'Grenada', continent: 'North America' },
  { code: 'gt', value: 'Guatemala', continent: 'North America' },
  { code: 'gn', value: 'Guinea', continent: 'Africa' },
  { code: 'gw', value: 'Guinea-Bissau', continent: 'Africa' },
  { code: 'gy', value: 'Guyana', continent: 'South America' },
  { code: 'ht', value: 'Haiti', continent: 'North America' },
  { code: 'hn', value: 'Honduras', continent: 'North America' },
  { code: 'hu', value: 'Hungary', continent: 'Europe' },
  { code: 'is', value: 'Iceland', continent: 'Europe' },
  { code: 'in', value: 'India', continent: 'Asia' },
  { code: 'id', value: 'Indonesia', continent: 'Asia' },
  { code: 'ir', value: 'Iran', continent: 'Asia' },
  { code: 'iq', value: 'Iraq', continent: 'Asia' },
  { code: 'ie', value: 'Ireland', continent: 'Europe' },
  { code: 'il', value: 'Israel', continent: 'Asia' },
  { code: 'it', value: 'Italy', continent: 'Europe' },
  { code: 'jm', value: 'Jamaica', continent: 'North America' },
  { code: 'jp', value: 'Japan', continent: 'Asia' },
  { code: 'jo', value: 'Jordan', continent: 'Asia' },
  { code: 'kz', value: 'Kazakhstan', continent: 'Asia' },
  { code: 'ke', value: 'Kenya', continent: 'Africa' },
  { code: 'kw', value: 'Kuwait', continent: 'Asia' },
  { code: 'kg', value: 'Kyrgyzstan', continent: 'Asia' },
  { code: 'la', value: 'Laos', continent: 'Asia' },
  { code: 'lv', value: 'Latvia', continent: 'Europe' },
  { code: 'lb', value: 'Lebanon', continent: 'Asia' },
  { code: 'ls', value: 'Lesotho', continent: 'Africa' },
  { code: 'lr', value: 'Liberia', continent: 'Africa' },
  { code: 'ly', value: 'Libya', continent: 'Africa' },
  { code: 'li', value: 'Liechtenstein', continent: 'Europe' },
  { code: 'lt', value: 'Lithuania', continent: 'Europe' },
  { code: 'lu', value: 'Luxembourg', continent: 'Europe' },
  { code: 'mg', value: 'Madagascar', continent: 'Africa' },
  { code: 'mw', value: 'Malawi', continent: 'Africa' },
  { code: 'my', value: 'Malaysia', continent: 'Asia' },
  { code: 'mv', value: 'Maldives', continent: 'Asia' },
  { code: 'ml', value: 'Mali', continent: 'Africa' },
  { code: 'mt', value: 'Malta', continent: 'Europe' },
  { code: 'mh', value: 'Marshall Islands', continent: 'Oceania' },
  { code: 'mr', value: 'Mauritania', continent: 'Africa' },
  { code: 'mu', value: 'Mauritius', continent: 'Africa' },
  { code: 'mx', value: 'Mexico', continent: 'North America' },
  { code: 'fm', value: 'Micronesia', continent: 'Oceania' },
  { code: 'md', value: 'Moldova', continent: 'Europe' },
  { code: 'mc', value: 'Monaco', continent: 'Europe' },
  { code: 'mn', value: 'Mongolia', continent: 'Asia' },
  { code: 'me', value: 'Montenegro', continent: 'Europe' },
  { code: 'ma', value: 'Morocco', continent: 'Africa' },
  { code: 'mz', value: 'Mozambique', continent: 'Africa' },
  { code: 'mm', value: 'Myanmar', continent: 'Asia' },
  { code: 'na', value: 'Namibia', continent: 'Africa' },
  { code: 'nr', value: 'Nauru', continent: 'Oceania' },
  { code: 'np', value: 'Nepal', continent: 'Asia' },
  { code: 'nl', value: 'Netherlands', continent: 'Europe' },
  { code: 'nz', value: 'New Zealand', continent: 'Oceania' },
  { code: 'ni', value: 'Nicaragua', continent: 'North America' },
  { code: 'ne', value: 'Niger', continent: 'Africa' },
  { code: 'ng', value: 'Nigeria', continent: 'Africa' },
  { code: 'kp', value: 'North Korea', continent: 'Asia' },
  { code: 'mk', value: 'North Macedonia', continent: 'Europe' },
  { code: 'no', value: 'Norway', continent: 'Europe' },
  { code: 'om', value: 'Oman', continent: 'Asia' },
  { code: 'pk', value: 'Pakistan', continent: 'Asia' },
  { code: 'pw', value: 'Palau', continent: 'Oceania' },
  { code: 'ps', value: 'Palestine', continent: 'Asia' },
  { code: 'pa', value: 'Panama', continent: 'North America' },
  { code: 'pg', value: 'Papua New Guinea', continent: 'Oceania' },
  { code: 'py', value: 'Paraguay', continent: 'South America' },
  { code: 'pe', value: 'Peru', continent: 'South America' },
  { code: 'ph', value: 'Philippines', continent: 'Asia' },
  { code: 'pl', value: 'Poland', continent: 'Europe' },
  { code: 'pt', value: 'Portugal', continent: 'Europe' },
  { code: 'qa', value: 'Qatar', continent: 'Asia' },
  { code: 'ro', value: 'Romania', continent: 'Europe' },
  { code: 'ru', value: 'Russia', continent: 'Europe' },
  { code: 'rw', value: 'Rwanda', continent: 'Africa' },
  { code: 'ws', value: 'Samoa', continent: 'Oceania' },
  { code: 'sm', value: 'San Marino', continent: 'Europe' },
  { code: 'sa', value: 'Saudi Arabia', continent: 'Asia' },
  { code: 'sn', value: 'Senegal', continent: 'Africa' },
  { code: 'rs', value: 'Serbia', continent: 'Europe' },
  { code: 'sc', value: 'Seychelles', continent: 'Africa' },
  { code: 'sl', value: 'Sierra Leone', continent: 'Africa' },
  { code: 'sg', value: 'Singapore', continent: 'Asia' },
  { code: 'sk', value: 'Slovakia', continent: 'Europe' },
  { code: 'si', value: 'Slovenia', continent: 'Europe' },
  { code: 'sb', value: 'Solomon Islands', continent: 'Oceania' },
  { code: 'so', value: 'Somalia', continent: 'Africa' },
  { code: 'za', value: 'South Africa', continent: 'Africa' },
  { code: 'kr', value: 'South Korea', continent: 'Asia' },
  { code: 'ss', value: 'South Sudan', continent: 'Africa' },
  { code: 'es', value: 'Spain', continent: 'Europe' },
  { code: 'lk', value: 'Sri Lanka', continent: 'Asia' },
  { code: 'sd', value: 'Sudan', continent: 'Africa' },
  { code: 'sr', value: 'Surivalue', continent: 'South America' },
  { code: 'se', value: 'Sweden', continent: 'Europe' },
  { code: 'ch', value: 'Switzerland', continent: 'Europe' },
  { code: 'sy', value: 'Syria', continent: 'Asia' },
  { code: 'tw', value: 'Taiwan', continent: 'Asia' },
  { code: 'tj', value: 'Tajikistan', continent: 'Asia' },
  { code: 'tz', value: 'Tanzania', continent: 'Africa' },
  { code: 'th', value: 'Thailand', continent: 'Asia' },
  { code: 'tl', value: 'Timor-Leste', continent: 'Asia' },
  { code: 'tg', value: 'Togo', continent: 'Africa' },
  { code: 'to', value: 'Tonga', continent: 'Oceania' },
  { code: 'tt', value: 'Trinidad and Tobago', continent: 'North America' },
  { code: 'tn', value: 'Tunisia', continent: 'Africa' },
  { code: 'tr', value: 'Turkey', continent: 'Asia' },
  { code: 'tm', value: 'Turkmenistan', continent: 'Asia' },
  { code: 'tv', value: 'Tuvalu', continent: 'Oceania' },
  { code: 'ug', value: 'Uganda', continent: 'Africa' },
  { code: 'ua', value: 'Ukraine', continent: 'Europe' },
  { code: 'ae', value: 'United Arab Emirates', continent: 'Asia' },
  { code: 'gb', value: 'United Kingdom', continent: 'Europe' },
  { code: 'us', value: 'United States', continent: 'North America' },
  { code: 'uy', value: 'Uruguay', continent: 'South America' },
  { code: 'uz', value: 'Uzbekistan', continent: 'Asia' },
  { code: 'vu', value: 'Vanuatu', continent: 'Oceania' },
  { code: 'va', value: 'Vatican City', continent: 'Europe' },
  { code: 've', value: 'Venezuela', continent: 'South America' },
  { code: 'vn', value: 'Vietnam', continent: 'Asia' },
  { code: 'ye', value: 'Yemen', continent: 'Asia' },
  { code: 'zm', value: 'Zambia', continent: 'Africa' },
  { code: 'zw', value: 'Zimbabwe', continent: 'Africa' },
];
