// AUTO-GENERATED by research/d-real-world-usage/_captures/gen-wild-highlights.mjs — do not
// edit by hand. Maps a docs "In the wild" card (Base UI component + site domain) to the
// screenshot + spotlight highlight captured from that site. `WildCard` looks entries up via
// the `component` prop on the enclosing `WildCards` plus the card's own `live`/`href`
// domain, falling back to a site-level (`*::domain`) capture when there's no per-component one.
/* eslint-disable import/no-relative-packages */
import img_9ui_accordion_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-accordion-hl.png';
import img_9ui_accordion_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-accordion-hl-highlight.png';
import img_lumiui_accordion_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-accordion-hl.png';
import img_lumiui_accordion_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-accordion-hl-highlight.png';
import img_reui_accordion_hl_page from '../../../../../research/d-real-world-usage/_captures/reui-accordion-hl.png';
import img_reui_accordion_hl_hi from '../../../../../research/d-real-world-usage/_captures/reui-accordion-hl-highlight.png';
import img_9ui_alert_dialog_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-alert-dialog-hl.png';
import img_9ui_alert_dialog_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-alert-dialog-hl-highlight.png';
import img_lumiui_alert_dialog_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-alert-dialog-hl.png';
import img_lumiui_alert_dialog_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-alert-dialog-hl-highlight.png';
import img_9ui_avatar_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-avatar-hl.png';
import img_9ui_avatar_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-avatar-hl-highlight.png';
import img_lumiui_avatar_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-avatar-hl.png';
import img_lumiui_avatar_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-avatar-hl-highlight.png';
import img_reui_avatar_hl_page from '../../../../../research/d-real-world-usage/_captures/reui-avatar-hl.png';
import img_reui_avatar_hl_hi from '../../../../../research/d-real-world-usage/_captures/reui-avatar-hl-highlight.png';
import img_9ui_button_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-button-hl.png';
import img_9ui_button_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-button-hl-highlight.png';
import img_9ui_checkbox_group_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-checkbox-group-hl.png';
import img_9ui_checkbox_group_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-checkbox-group-hl-highlight.png';
import img_coss_checkbox_group_hl_page from '../../../../../research/d-real-world-usage/_captures/coss-checkbox-group-hl.png';
import img_coss_checkbox_group_hl_hi from '../../../../../research/d-real-world-usage/_captures/coss-checkbox-group-hl-highlight.png';
import img_lumiui_checkbox_group_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-checkbox-group-hl.png';
import img_lumiui_checkbox_group_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-checkbox-group-hl-highlight.png';
import img_coss_checkbox_hl_page from '../../../../../research/d-real-world-usage/_captures/coss-checkbox-hl.png';
import img_coss_checkbox_hl_hi from '../../../../../research/d-real-world-usage/_captures/coss-checkbox-hl-highlight.png';
import img_reui_checkbox_hl_page from '../../../../../research/d-real-world-usage/_captures/reui-checkbox-hl.png';
import img_reui_checkbox_hl_hi from '../../../../../research/d-real-world-usage/_captures/reui-checkbox-hl-highlight.png';
import img_9ui_collapsible_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-collapsible-hl.png';
import img_9ui_collapsible_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-collapsible-hl-highlight.png';
import img_coss_context_menu_hl_page from '../../../../../research/d-real-world-usage/_captures/coss-context-menu-hl.png';
import img_coss_context_menu_hl_hi from '../../../../../research/d-real-world-usage/_captures/coss-context-menu-hl-highlight.png';
import img_lumiui_context_menu_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-context-menu-hl.png';
import img_lumiui_context_menu_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-context-menu-hl-highlight.png';
import img_reui_context_menu_hl_page from '../../../../../research/d-real-world-usage/_captures/reui-context-menu-hl.png';
import img_reui_context_menu_hl_hi from '../../../../../research/d-real-world-usage/_captures/reui-context-menu-hl-highlight.png';
import img_coss_drawer_hl_page from '../../../../../research/d-real-world-usage/_captures/coss-drawer-hl.png';
import img_coss_drawer_hl_hi from '../../../../../research/d-real-world-usage/_captures/coss-drawer-hl-highlight.png';
import img_reui_drawer_hl_page from '../../../../../research/d-real-world-usage/_captures/reui-drawer-hl.png';
import img_reui_drawer_hl_hi from '../../../../../research/d-real-world-usage/_captures/reui-drawer-hl-highlight.png';
import img_coss_fieldset_hl_page from '../../../../../research/d-real-world-usage/_captures/coss-fieldset-hl.png';
import img_coss_fieldset_hl_hi from '../../../../../research/d-real-world-usage/_captures/coss-fieldset-hl-highlight.png';
import img_lumiui_fieldset_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-fieldset-hl.png';
import img_lumiui_fieldset_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-fieldset-hl-highlight.png';
import img_9ui_input_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-input-hl.png';
import img_9ui_input_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-input-hl-highlight.png';
import img_lumiui_menubar_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-menubar-hl.png';
import img_lumiui_menubar_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-menubar-hl-highlight.png';
import img_9ui_meter_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-meter-hl.png';
import img_9ui_meter_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-meter-hl-highlight.png';
import img_lumiui_meter_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-meter-hl.png';
import img_lumiui_meter_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-meter-hl-highlight.png';
import img_9ui_navigation_menu_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-navigation-menu-hl.png';
import img_9ui_navigation_menu_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-navigation-menu-hl-highlight.png';
import img_lumiui_navigation_menu_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-navigation-menu-hl.png';
import img_lumiui_navigation_menu_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-navigation-menu-hl-highlight.png';
import img_9ui_number_field_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-number-field-hl.png';
import img_9ui_number_field_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-number-field-hl-highlight.png';
import img_coss_number_field_hl_page from '../../../../../research/d-real-world-usage/_captures/coss-number-field-hl.png';
import img_coss_number_field_hl_hi from '../../../../../research/d-real-world-usage/_captures/coss-number-field-hl-highlight.png';
import img_lumiui_number_field_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-number-field-hl.png';
import img_lumiui_number_field_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-number-field-hl-highlight.png';
import img_9ui_otp_field_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-otp-field-hl.png';
import img_9ui_otp_field_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-otp-field-hl-highlight.png';
import img_coss_otp_field_hl_page from '../../../../../research/d-real-world-usage/_captures/coss-otp-field-hl.png';
import img_coss_otp_field_hl_hi from '../../../../../research/d-real-world-usage/_captures/coss-otp-field-hl-highlight.png';
import img_lumiui_otp_field_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-otp-field-hl.png';
import img_lumiui_otp_field_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-otp-field-hl-highlight.png';
import img_9ui_preview_card_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-preview-card-hl.png';
import img_9ui_preview_card_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-preview-card-hl-highlight.png';
import img_coss_preview_card_hl_page from '../../../../../research/d-real-world-usage/_captures/coss-preview-card-hl.png';
import img_coss_preview_card_hl_hi from '../../../../../research/d-real-world-usage/_captures/coss-preview-card-hl-highlight.png';
import img_lumiui_preview_card_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-preview-card-hl.png';
import img_lumiui_preview_card_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-preview-card-hl-highlight.png';
import img_9ui_progress_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-progress-hl.png';
import img_9ui_progress_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-progress-hl-highlight.png';
import img_coss_progress_hl_page from '../../../../../research/d-real-world-usage/_captures/coss-progress-hl.png';
import img_coss_progress_hl_hi from '../../../../../research/d-real-world-usage/_captures/coss-progress-hl-highlight.png';
import img_lumiui_progress_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-progress-hl.png';
import img_lumiui_progress_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-progress-hl-highlight.png';
import img_9ui_radio_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-radio-hl.png';
import img_9ui_radio_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-radio-hl-highlight.png';
import img_9ui_scroll_area_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-scroll-area-hl.png';
import img_9ui_scroll_area_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-scroll-area-hl-highlight.png';
import img_lumiui_scroll_area_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-scroll-area-hl.png';
import img_lumiui_scroll_area_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-scroll-area-hl-highlight.png';
import img_reui_scroll_area_hl_page from '../../../../../research/d-real-world-usage/_captures/reui-scroll-area-hl.png';
import img_reui_scroll_area_hl_hi from '../../../../../research/d-real-world-usage/_captures/reui-scroll-area-hl-highlight.png';
import img_9ui_slider_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-slider-hl.png';
import img_9ui_slider_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-slider-hl-highlight.png';
import img_coss_slider_hl_page from '../../../../../research/d-real-world-usage/_captures/coss-slider-hl.png';
import img_coss_slider_hl_hi from '../../../../../research/d-real-world-usage/_captures/coss-slider-hl-highlight.png';
import img_lumiui_slider_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-slider-hl.png';
import img_lumiui_slider_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-slider-hl-highlight.png';
import img_reui_switch_hl_page from '../../../../../research/d-real-world-usage/_captures/reui-switch-hl.png';
import img_reui_switch_hl_hi from '../../../../../research/d-real-world-usage/_captures/reui-switch-hl-highlight.png';
import img_9ui_tabs_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-tabs-hl.png';
import img_9ui_tabs_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-tabs-hl-highlight.png';
import img_lumiui_toast_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-toast-hl.png';
import img_lumiui_toast_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-toast-hl-highlight.png';
import img_9ui_toggle_group_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-toggle-group-hl.png';
import img_9ui_toggle_group_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-toggle-group-hl-highlight.png';
import img_lumiui_toggle_group_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-toggle-group-hl.png';
import img_lumiui_toggle_group_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-toggle-group-hl-highlight.png';
import img_coss_toggle_hl_page from '../../../../../research/d-real-world-usage/_captures/coss-toggle-hl.png';
import img_coss_toggle_hl_hi from '../../../../../research/d-real-world-usage/_captures/coss-toggle-hl-highlight.png';
import img_reui_toggle_hl_page from '../../../../../research/d-real-world-usage/_captures/reui-toggle-hl.png';
import img_reui_toggle_hl_hi from '../../../../../research/d-real-world-usage/_captures/reui-toggle-hl-highlight.png';
import img_9ui_toolbar_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-toolbar-hl.png';
import img_9ui_toolbar_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-toolbar-hl-highlight.png';
import img_lumiui_toolbar_hl_page from '../../../../../research/d-real-world-usage/_captures/lumiui-toolbar-hl.png';
import img_lumiui_toolbar_hl_hi from '../../../../../research/d-real-world-usage/_captures/lumiui-toolbar-hl-highlight.png';
import img_reui_tooltip_hl_page from '../../../../../research/d-real-world-usage/_captures/reui-tooltip-hl.png';
import img_reui_tooltip_hl_hi from '../../../../../research/d-real-world-usage/_captures/reui-tooltip-hl-highlight.png';
import img_ui_shadcn_com_hl_page from '../../../../../research/d-real-world-usage/_captures/ui-shadcn-com-hl.png';
import img_ui_shadcn_com_hl_hi from '../../../../../research/d-real-world-usage/_captures/ui-shadcn-com-hl-highlight.png';
import img_graphql_org_hl_page from '../../../../../research/d-real-world-usage/_captures/graphql-org-hl.png';
import img_graphql_org_hl_hi from '../../../../../research/d-real-world-usage/_captures/graphql-org-hl-highlight.png';
import img_kumo_ui_com_hl_page from '../../../../../research/d-real-world-usage/_captures/kumo-ui-com-hl.png';
import img_kumo_ui_com_hl_hi from '../../../../../research/d-real-world-usage/_captures/kumo-ui-com-hl-highlight.png';
import img_mastra_ai_hl_page from '../../../../../research/d-real-world-usage/_captures/mastra-ai-hl.png';
import img_mastra_ai_hl_hi from '../../../../../research/d-real-world-usage/_captures/mastra-ai-hl-highlight.png';
import img_nextjs_org_hl_page from '../../../../../research/d-real-world-usage/_captures/nextjs-org-hl.png';
import img_nextjs_org_hl_hi from '../../../../../research/d-real-world-usage/_captures/nextjs-org-hl-highlight.png';
import img_posthog_com_hl_page from '../../../../../research/d-real-world-usage/_captures/posthog-com-hl.png';
import img_posthog_com_hl_hi from '../../../../../research/d-real-world-usage/_captures/posthog-com-hl-highlight.png';
import img_wordpress_org_gutenberg_hl_page from '../../../../../research/d-real-world-usage/_captures/wordpress-org-gutenberg-hl.png';
import img_wordpress_org_gutenberg_hl_hi from '../../../../../research/d-real-world-usage/_captures/wordpress-org-gutenberg-hl-highlight.png';
import img_zweien_github_io_docx_template_system_hl_page from '../../../../../research/d-real-world-usage/_captures/zweien-github-io-docx-template-system-hl.png';
import img_zweien_github_io_docx_template_system_hl_hi from '../../../../../research/d-real-world-usage/_captures/zweien-github-io-docx-template-system-hl-highlight.png';
import img_9ui_dev_hl_page from '../../../../../research/d-real-world-usage/_captures/9ui-dev-hl.png';
import img_9ui_dev_hl_hi from '../../../../../research/d-real-world-usage/_captures/9ui-dev-hl-highlight.png';
import img_reui_io_hl_page from '../../../../../research/d-real-world-usage/_captures/reui-io-hl.png';
import img_reui_io_hl_hi from '../../../../../research/d-real-world-usage/_captures/reui-io-hl-highlight.png';
/* eslint-enable import/no-relative-packages */

export interface WildHighlight {
  /** The page screenshot (same frame as the highlight). */
  image: string;
  /** The spotlight screenshot (page dimmed, component outlined). */
  highlightImage: string;
  /** Concrete CSS selector to the component on the page. */
  selector: string;
  /** URL pathname of the page. */
  route: string;
  /** Full page URL the screenshots came from. */
  pageUrl: string;
}

/** Keyed by `${component}::${domain}` or the site-level `*::${domain}`. */
export const wildHighlights: Record<string, WildHighlight> = {
  '*::9ui.dev': {
    image: img_9ui_dev_hl_page,
    highlightImage: img_9ui_dev_hl_hi,
    selector: '[role="tablist"]',
    route: '/',
    pageUrl: 'https://www.9ui.dev',
  },
  '*::graphql.org': {
    image: img_graphql_org_hl_page,
    highlightImage: img_graphql_org_hl_hi,
    selector: '[role="combobox"]',
    route: '/',
    pageUrl: 'https://graphql.org',
  },
  '*::kumo-ui.com': {
    image: img_kumo_ui_com_hl_page,
    highlightImage: img_kumo_ui_com_hl_hi,
    selector: '[role="combobox"]',
    route: '/',
    pageUrl: 'https://kumo-ui.com',
  },
  '*::mastra.ai': {
    image: img_mastra_ai_hl_page,
    highlightImage: img_mastra_ai_hl_hi,
    selector: '[role="tablist"]',
    route: '/',
    pageUrl: 'https://mastra.ai',
  },
  '*::nextjs.org': {
    image: img_nextjs_org_hl_page,
    highlightImage: img_nextjs_org_hl_hi,
    selector: '[role="radiogroup"]',
    route: '/',
    pageUrl: 'https://nextjs.org',
  },
  '*::posthog.com': {
    image: img_posthog_com_hl_page,
    highlightImage: img_posthog_com_hl_hi,
    selector: '[role="menubar"]',
    route: '/',
    pageUrl: 'https://posthog.com',
  },
  '*::reui.io': {
    image: img_reui_io_hl_page,
    highlightImage: img_reui_io_hl_hi,
    selector: '[role="combobox"]',
    route: '/',
    pageUrl: 'https://reui.io',
  },
  '*::ui.shadcn.com': {
    image: img_ui_shadcn_com_hl_page,
    highlightImage: img_ui_shadcn_com_hl_hi,
    selector: '[role="radiogroup"]',
    route: '/',
    pageUrl: 'https://ui.shadcn.com',
  },
  '*::wordpress.org': {
    image: img_wordpress_org_gutenberg_hl_page,
    highlightImage: img_wordpress_org_gutenberg_hl_hi,
    selector: '[role="tablist"]',
    route: '/gutenberg/',
    pageUrl: 'https://wordpress.org/gutenberg/',
  },
  '*::zweien.github.io': {
    image: img_zweien_github_io_docx_template_system_hl_page,
    highlightImage: img_zweien_github_io_docx_template_system_hl_hi,
    selector: '[role="combobox"]',
    route: '/docx-template-system/',
    pageUrl: 'https://zweien.github.io/docx-template-system/',
  },
  'accordion::9ui.dev': {
    image: img_9ui_accordion_hl_page,
    highlightImage: img_9ui_accordion_hl_hi,
    selector: '[data-slot="accordion"]',
    route: '/docs/components/accordion',
    pageUrl: 'https://www.9ui.dev/docs/components/accordion',
  },
  'accordion::lumiui.dev': {
    image: img_lumiui_accordion_hl_page,
    highlightImage: img_lumiui_accordion_hl_hi,
    selector: '[data-slot="accordion"]',
    route: '/docs/components/layout-nav/accordion',
    pageUrl: 'https://www.lumiui.dev/docs/components/layout-nav/accordion',
  },
  'accordion::reui.io': {
    image: img_reui_accordion_hl_page,
    highlightImage: img_reui_accordion_hl_hi,
    selector: '[data-slot="accordion"]',
    route: '/components/accordion',
    pageUrl: 'https://reui.io/components/accordion',
  },
  'alert-dialog::9ui.dev': {
    image: img_9ui_alert_dialog_hl_page,
    highlightImage: img_9ui_alert_dialog_hl_hi,
    selector: '[data-slot^="alert-dialog"]',
    route: '/docs/components/alert-dialog',
    pageUrl: 'https://www.9ui.dev/docs/components/alert-dialog',
  },
  'alert-dialog::lumiui.dev': {
    image: img_lumiui_alert_dialog_hl_page,
    highlightImage: img_lumiui_alert_dialog_hl_hi,
    selector: '[data-slot^="alert-dialog"]',
    route: '/docs/components/overlays-dialogs/alert-dialog',
    pageUrl: 'https://www.lumiui.dev/docs/components/overlays-dialogs/alert-dialog',
  },
  'avatar::9ui.dev': {
    image: img_9ui_avatar_hl_page,
    highlightImage: img_9ui_avatar_hl_hi,
    selector: '[data-slot="avatar"]',
    route: '/docs/components/avatar',
    pageUrl: 'https://www.9ui.dev/docs/components/avatar',
  },
  'avatar::lumiui.dev': {
    image: img_lumiui_avatar_hl_page,
    highlightImage: img_lumiui_avatar_hl_hi,
    selector: '[data-slot="avatar"]',
    route: '/docs/components/display-media/avatar',
    pageUrl: 'https://www.lumiui.dev/docs/components/display-media/avatar',
  },
  'avatar::reui.io': {
    image: img_reui_avatar_hl_page,
    highlightImage: img_reui_avatar_hl_hi,
    selector: '[data-slot="avatar"]',
    route: '/components/avatar',
    pageUrl: 'https://reui.io/components/avatar',
  },
  'button::9ui.dev': {
    image: img_9ui_button_hl_page,
    highlightImage: img_9ui_button_hl_hi,
    selector: '[data-slot="button"]',
    route: '/docs/components/button',
    pageUrl: 'https://www.9ui.dev/docs/components/button',
  },
  'checkbox-group::9ui.dev': {
    image: img_9ui_checkbox_group_hl_page,
    highlightImage: img_9ui_checkbox_group_hl_hi,
    selector: '[role="checkbox"]',
    route: '/docs/components/checkbox-group',
    pageUrl: 'https://www.9ui.dev/docs/components/checkbox-group',
  },
  'checkbox-group::coss.com': {
    image: img_coss_checkbox_group_hl_page,
    highlightImage: img_coss_checkbox_group_hl_hi,
    selector: '[role="checkbox"]',
    route: '/ui/docs/components/checkbox-group',
    pageUrl: 'https://coss.com/ui/docs/components/checkbox-group',
  },
  'checkbox-group::lumiui.dev': {
    image: img_lumiui_checkbox_group_hl_page,
    highlightImage: img_lumiui_checkbox_group_hl_hi,
    selector: '[role="checkbox"]',
    route: '/docs/components/form-input/checkbox-group',
    pageUrl: 'https://www.lumiui.dev/docs/components/form-input/checkbox-group',
  },
  'checkbox::coss.com': {
    image: img_coss_checkbox_hl_page,
    highlightImage: img_coss_checkbox_hl_hi,
    selector: '[role="checkbox"]',
    route: '/ui/docs/components/checkbox',
    pageUrl: 'https://coss.com/ui/docs/components/checkbox',
  },
  'checkbox::reui.io': {
    image: img_reui_checkbox_hl_page,
    highlightImage: img_reui_checkbox_hl_hi,
    selector: '[role="checkbox"]',
    route: '/components/checkbox',
    pageUrl: 'https://reui.io/components/checkbox',
  },
  'collapsible::9ui.dev': {
    image: img_9ui_collapsible_hl_page,
    highlightImage: img_9ui_collapsible_hl_hi,
    selector: '[data-slot^="collapsible"]',
    route: '/docs/components/collapsible',
    pageUrl: 'https://www.9ui.dev/docs/components/collapsible',
  },
  'context-menu::coss.com': {
    image: img_coss_context_menu_hl_page,
    highlightImage: img_coss_context_menu_hl_hi,
    selector: '[data-slot^="context-menu"]',
    route: '/ui/docs/components/context-menu',
    pageUrl: 'https://coss.com/ui/docs/components/context-menu',
  },
  'context-menu::lumiui.dev': {
    image: img_lumiui_context_menu_hl_page,
    highlightImage: img_lumiui_context_menu_hl_hi,
    selector: '[data-slot^="context-menu"]',
    route: '/docs/components/overlays-dialogs/context-menu',
    pageUrl: 'https://www.lumiui.dev/docs/components/overlays-dialogs/context-menu',
  },
  'context-menu::reui.io': {
    image: img_reui_context_menu_hl_page,
    highlightImage: img_reui_context_menu_hl_hi,
    selector: '[data-slot^="context-menu"]',
    route: '/components/context-menu',
    pageUrl: 'https://reui.io/components/context-menu',
  },
  'drawer::coss.com': {
    image: img_coss_drawer_hl_page,
    highlightImage: img_coss_drawer_hl_hi,
    selector: '[data-slot^="drawer"]',
    route: '/ui/docs/components/drawer',
    pageUrl: 'https://coss.com/ui/docs/components/drawer',
  },
  'drawer::reui.io': {
    image: img_reui_drawer_hl_page,
    highlightImage: img_reui_drawer_hl_hi,
    selector: '[data-slot^="drawer"]',
    route: '/components/drawer',
    pageUrl: 'https://reui.io/components/drawer',
  },
  'fieldset::coss.com': {
    image: img_coss_fieldset_hl_page,
    highlightImage: img_coss_fieldset_hl_hi,
    selector: 'fieldset',
    route: '/ui/docs/components/fieldset',
    pageUrl: 'https://coss.com/ui/docs/components/fieldset',
  },
  'fieldset::lumiui.dev': {
    image: img_lumiui_fieldset_hl_page,
    highlightImage: img_lumiui_fieldset_hl_hi,
    selector: 'fieldset',
    route: '/docs/components/form-input/fieldset',
    pageUrl: 'https://www.lumiui.dev/docs/components/form-input/fieldset',
  },
  'input::9ui.dev': {
    image: img_9ui_input_hl_page,
    highlightImage: img_9ui_input_hl_hi,
    selector: '[data-slot="input"]',
    route: '/docs/components/input',
    pageUrl: 'https://www.9ui.dev/docs/components/input',
  },
  'menubar::lumiui.dev': {
    image: img_lumiui_menubar_hl_page,
    highlightImage: img_lumiui_menubar_hl_hi,
    selector: '[role="menubar"]',
    route: '/docs/components/misc/menubar',
    pageUrl: 'https://www.lumiui.dev/docs/components/misc/menubar',
  },
  'meter::9ui.dev': {
    image: img_9ui_meter_hl_page,
    highlightImage: img_9ui_meter_hl_hi,
    selector: '[role="meter"]',
    route: '/docs/components/meter',
    pageUrl: 'https://www.9ui.dev/docs/components/meter',
  },
  'meter::lumiui.dev': {
    image: img_lumiui_meter_hl_page,
    highlightImage: img_lumiui_meter_hl_hi,
    selector: '[role="meter"]',
    route: '/docs/components/feedback-status/meter',
    pageUrl: 'https://www.lumiui.dev/docs/components/feedback-status/meter',
  },
  'navigation-menu::9ui.dev': {
    image: img_9ui_navigation_menu_hl_page,
    highlightImage: img_9ui_navigation_menu_hl_hi,
    selector: '[data-slot^="navigation-menu"]',
    route: '/docs/components/navigation-menu',
    pageUrl: 'https://www.9ui.dev/docs/components/navigation-menu',
  },
  'navigation-menu::lumiui.dev': {
    image: img_lumiui_navigation_menu_hl_page,
    highlightImage: img_lumiui_navigation_menu_hl_hi,
    selector: '[data-slot^="navigation-menu"]',
    route: '/docs/components/layout-nav/navigation-menu',
    pageUrl: 'https://www.lumiui.dev/docs/components/layout-nav/navigation-menu',
  },
  'number-field::9ui.dev': {
    image: img_9ui_number_field_hl_page,
    highlightImage: img_9ui_number_field_hl_hi,
    selector: '[data-slot^="number-field"]',
    route: '/docs/components/number-field',
    pageUrl: 'https://www.9ui.dev/docs/components/number-field',
  },
  'number-field::coss.com': {
    image: img_coss_number_field_hl_page,
    highlightImage: img_coss_number_field_hl_hi,
    selector: '[data-slot^="number-field"]',
    route: '/ui/docs/components/number-field',
    pageUrl: 'https://coss.com/ui/docs/components/number-field',
  },
  'number-field::lumiui.dev': {
    image: img_lumiui_number_field_hl_page,
    highlightImage: img_lumiui_number_field_hl_hi,
    selector: '[data-slot^="number-field"]',
    route: '/docs/components/form-input/number-field',
    pageUrl: 'https://www.lumiui.dev/docs/components/form-input/number-field',
  },
  'otp-field::9ui.dev': {
    image: img_9ui_otp_field_hl_page,
    highlightImage: img_9ui_otp_field_hl_hi,
    selector: '[data-slot^="input-otp"], [data-slot^="otp"], [autocomplete="one-time-code"]',
    route: '/docs/components/input-otp',
    pageUrl: 'https://www.9ui.dev/docs/components/input-otp',
  },
  'otp-field::coss.com': {
    image: img_coss_otp_field_hl_page,
    highlightImage: img_coss_otp_field_hl_hi,
    selector: '[data-slot^="otp"]',
    route: '/ui/docs/components/otp-field',
    pageUrl: 'https://coss.com/ui/docs/components/otp-field',
  },
  'otp-field::lumiui.dev': {
    image: img_lumiui_otp_field_hl_page,
    highlightImage: img_lumiui_otp_field_hl_hi,
    selector: '[data-slot^="otp"]',
    route: '/docs/components/form-input/otp-field',
    pageUrl: 'https://www.lumiui.dev/docs/components/form-input/otp-field',
  },
  'preview-card::9ui.dev': {
    image: img_9ui_preview_card_hl_page,
    highlightImage: img_9ui_preview_card_hl_hi,
    selector: '[data-slot^="preview-card"], [data-slot^="hover-card"]',
    route: '/docs/components/preview-card',
    pageUrl: 'https://www.9ui.dev/docs/components/preview-card',
  },
  'preview-card::coss.com': {
    image: img_coss_preview_card_hl_page,
    highlightImage: img_coss_preview_card_hl_hi,
    selector: '[data-slot^="preview-card"], [data-slot^="hover-card"]',
    route: '/ui/docs/components/preview-card',
    pageUrl: 'https://coss.com/ui/docs/components/preview-card',
  },
  'preview-card::lumiui.dev': {
    image: img_lumiui_preview_card_hl_page,
    highlightImage: img_lumiui_preview_card_hl_hi,
    selector: '[data-slot^="preview-card"], [data-slot^="hover-card"]',
    route: '/docs/components/overlays-dialogs/preview-card',
    pageUrl: 'https://www.lumiui.dev/docs/components/overlays-dialogs/preview-card',
  },
  'progress::9ui.dev': {
    image: img_9ui_progress_hl_page,
    highlightImage: img_9ui_progress_hl_hi,
    selector: '[role="progressbar"]',
    route: '/docs/components/progress',
    pageUrl: 'https://www.9ui.dev/docs/components/progress',
  },
  'progress::coss.com': {
    image: img_coss_progress_hl_page,
    highlightImage: img_coss_progress_hl_hi,
    selector: '[role="progressbar"]',
    route: '/ui/docs/components/progress',
    pageUrl: 'https://coss.com/ui/docs/components/progress',
  },
  'progress::lumiui.dev': {
    image: img_lumiui_progress_hl_page,
    highlightImage: img_lumiui_progress_hl_hi,
    selector: '[role="progressbar"]',
    route: '/docs/components/feedback-status/progress',
    pageUrl: 'https://www.lumiui.dev/docs/components/feedback-status/progress',
  },
  'radio::9ui.dev': {
    image: img_9ui_radio_hl_page,
    highlightImage: img_9ui_radio_hl_hi,
    selector: '[role="radio"]',
    route: '/docs/components/radio-group',
    pageUrl: 'https://www.9ui.dev/docs/components/radio-group',
  },
  'scroll-area::9ui.dev': {
    image: img_9ui_scroll_area_hl_page,
    highlightImage: img_9ui_scroll_area_hl_hi,
    selector: '[data-slot="scroll-area"]',
    route: '/docs/components/scroll-area',
    pageUrl: 'https://www.9ui.dev/docs/components/scroll-area',
  },
  'scroll-area::lumiui.dev': {
    image: img_lumiui_scroll_area_hl_page,
    highlightImage: img_lumiui_scroll_area_hl_hi,
    selector: '[data-slot="scroll-area"]',
    route: '/docs/components/layout-nav/scroll-area',
    pageUrl: 'https://www.lumiui.dev/docs/components/layout-nav/scroll-area',
  },
  'scroll-area::reui.io': {
    image: img_reui_scroll_area_hl_page,
    highlightImage: img_reui_scroll_area_hl_hi,
    selector: '[data-slot="scroll-area"]',
    route: '/components/scroll-area',
    pageUrl: 'https://reui.io/components/scroll-area',
  },
  'slider::9ui.dev': {
    image: img_9ui_slider_hl_page,
    highlightImage: img_9ui_slider_hl_hi,
    selector: '[role="group"]',
    route: '/docs/components/slider',
    pageUrl: 'https://www.9ui.dev/docs/components/slider',
  },
  'slider::coss.com': {
    image: img_coss_slider_hl_page,
    highlightImage: img_coss_slider_hl_hi,
    selector: '[data-slot="preview"]',
    route: '/ui/docs/components/slider',
    pageUrl: 'https://coss.com/ui/docs/components/slider',
  },
  'slider::lumiui.dev': {
    image: img_lumiui_slider_hl_page,
    highlightImage: img_lumiui_slider_hl_hi,
    selector: '[role="group"]',
    route: '/docs/components/form-input/slider',
    pageUrl: 'https://www.lumiui.dev/docs/components/form-input/slider',
  },
  'switch::reui.io': {
    image: img_reui_switch_hl_page,
    highlightImage: img_reui_switch_hl_hi,
    selector: '[role="switch"]',
    route: '/components/switch',
    pageUrl: 'https://reui.io/components/switch',
  },
  'tabs::9ui.dev': {
    image: img_9ui_tabs_hl_page,
    highlightImage: img_9ui_tabs_hl_hi,
    selector: '[role="tablist"]',
    route: '/docs/components/tabs',
    pageUrl: 'https://www.9ui.dev/docs/components/tabs',
  },
  'toast::lumiui.dev': {
    image: img_lumiui_toast_hl_page,
    highlightImage: img_lumiui_toast_hl_hi,
    selector: '[data-slot^="toast"]',
    route: '/docs/components/feedback-status/toast',
    pageUrl: 'https://www.lumiui.dev/docs/components/feedback-status/toast',
  },
  'toggle-group::9ui.dev': {
    image: img_9ui_toggle_group_hl_page,
    highlightImage: img_9ui_toggle_group_hl_hi,
    selector: '[data-slot="toggle-group"]',
    route: '/docs/components/toggle-group',
    pageUrl: 'https://www.9ui.dev/docs/components/toggle-group',
  },
  'toggle-group::lumiui.dev': {
    image: img_lumiui_toggle_group_hl_page,
    highlightImage: img_lumiui_toggle_group_hl_hi,
    selector: '[data-slot="toggle-group"]',
    route: '/docs/components/misc/toggle-group',
    pageUrl: 'https://www.lumiui.dev/docs/components/misc/toggle-group',
  },
  'toggle::coss.com': {
    image: img_coss_toggle_hl_page,
    highlightImage: img_coss_toggle_hl_hi,
    selector: '[data-slot="toggle"]',
    route: '/ui/docs/components/toggle',
    pageUrl: 'https://coss.com/ui/docs/components/toggle',
  },
  'toggle::reui.io': {
    image: img_reui_toggle_hl_page,
    highlightImage: img_reui_toggle_hl_hi,
    selector: '[data-slot="toggle"]',
    route: '/components/toggle',
    pageUrl: 'https://reui.io/components/toggle',
  },
  'toolbar::9ui.dev': {
    image: img_9ui_toolbar_hl_page,
    highlightImage: img_9ui_toolbar_hl_hi,
    selector: '[role="toolbar"]',
    route: '/docs/components/toolbar',
    pageUrl: 'https://www.9ui.dev/docs/components/toolbar',
  },
  'toolbar::lumiui.dev': {
    image: img_lumiui_toolbar_hl_page,
    highlightImage: img_lumiui_toolbar_hl_hi,
    selector: '[role="toolbar"]',
    route: '/docs/components/misc/toolbar',
    pageUrl: 'https://www.lumiui.dev/docs/components/misc/toolbar',
  },
  'tooltip::reui.io': {
    image: img_reui_tooltip_hl_page,
    highlightImage: img_reui_tooltip_hl_hi,
    selector: '[data-slot^="tooltip"]',
    route: '/components/tooltip',
    pageUrl: 'https://reui.io/components/tooltip',
  },
};

/** Normalize a card's `live`/`href` URL to the bare domain used as the registry key. */
export function highlightDomain(url: string | undefined): string | null {
  if (!url) {
    return null;
  }
  try {
    return new URL(url).hostname.replace(/^www\./, '');
  } catch {
    return null;
  }
}

export function lookupHighlight(
  component: string | undefined,
  url: string | undefined,
): WildHighlight | undefined {
  const domain = highlightDomain(url);
  if (!domain) {
    return undefined;
  }
  return (
    (component ? wildHighlights[`${component}::${domain}`] : undefined) ??
    wildHighlights[`*::${domain}`]
  );
}
