name: CI

on:
  push:
    branches-ignore:
      # Renovate branches are always Pull Requests.
      # We don't need to run CI twice (push+pull_request)
      - 'renovate/**'
      - 'dependabot/**'
  pull_request:

permissions: {}

jobs:
  # Tests dev-only scripts across all supported dev environments
  test-dev:
    # l10nbot does not affect dev scripts.
    if: ${{ github.actor != 'l10nbot' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: echo "${{ github.actor }}"
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # fetch all tags which are required for `pnpm release:changelog`
          fetch-depth: 0
      - name: Set up pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
      - name: Use Node.js 22.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '22.18'
          cache: 'pnpm' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
      - run: pnpm install
      - run: pnpm release:build
      - name: Publish packages
        if: matrix.os == 'ubuntu-latest'
        uses: mui/mui-public/.github/actions/ci-publish@1d16a59f8f43b3527070678bb7d872c32e0a6cac
        with:
          pr-comment: true
      - name: Extract Vale version
        if: ${{ matrix.os == 'ubuntu-latest' }}
        id: vale-version
        run: |
          VERSION=$(node -p "(require('./package.json').config && require('./package.json').config.valeVersion) || ''")
          echo "vale_version=$VERSION" >> $GITHUB_OUTPUT
      - uses: vale-cli/vale-action@d89dee975228ae261d22c15adcd03578634d429c # v2.1.1
        continue-on-error: true # GitHub Action flag needed until https://github.com/errata-ai/vale-action/issues/89 is fixed
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          version: ${{ steps.vale-version.outputs.vale_version }}
          # Errors should be more visible
          fail_on_error: true
          # The other reports don't work, not really https://github.com/reviewdog/reviewdog#reporters
          reporter: github-pr-check
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          token: ${{secrets.GITHUB_TOKEN}}
