name: Add closing message to issue

on:
  issues:
    types:
      - closed

permissions: {}

jobs:
  add-comment:
    name: Add closing message
    uses: mui/mui-public/.github/workflows/issues_add-closing-message.yml@master
    permissions:
      contents: read
      issues: write
