name: New issue triage
on:
  issues:
    types:
      - opened

permissions: {}

jobs:
  issue_cleanup:
    name: Clean issue body
    uses: mui/mui-public/.github/workflows/issues_body-cleanup.yml@07ed00b7c0b558d9dbaaaab9fe6a8e76784d77b3 # master
    permissions:
      contents: read
      issues: write
