name: New issue triage
on:
  issues:
    types:
      - opened

permissions: {}

jobs:
  issue_cleanup:
    name: Clean issue body
    uses: mui/mui-public/.github/workflows/issues_body-cleanup.yml@03f5d78b7f16c1b7375e67c9270475126d63464c
    permissions:
      contents: read
      issues: write
